# Config File

path_genome: "data/genome.fa"
path_gtf: "data/annotation.gtf"
path_transcriptome: "data/transcripts.fasta"

params:
  genomeindex: ""
  eggnogdatabase: "33208"
  emapper: "-m diamond --sensmode sensitive --target_orthologs all --go_evidence non-electronic"
  hmmer_url: "https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz"
  swissprot_url: "https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz"